import = ["/Users/ae/.config/alacritty/themes/ayu_dark.toml"]

[font]
size = 15

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Iosevka Comfy"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "S"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Command"

[window.padding]
x = 8
y = 4
