# Prompt format string.
format = """
$directory\
$git_branch\
$git_status\
$status\
$character"""

[git_branch]
format = "([$branch]($style) )"
truncation_length = 16
truncation_symbol = "..."

[git_status]
format = "([$conflicted$modified$deleted$renamed$staged$untracked$stashed$ahead_behind]($style) )"
style = "blue"
conflicted = "c"
modified = "*"
deleted = "x"
renamed = "»"
staged = "+"
untracked = "?"
stashed = "\\$"

[status]
disabled = false
format = "([$status]($style) )"