#!/usr/bin/env sh

# Load the yabai scripting addition (required on newer versions of macOS).
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Base settings
yabai -m config layout                       bsp
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float

# Opacity settings
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9

# Border settings
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff87bbd4
yabai -m config normal_window_border_color   0xff8d94a1

# Split settings
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse settings
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

# Padding settings
yabai -m config top_padding                  02
yabai -m config bottom_padding               02
yabai -m config left_padding                 02
yabai -m config right_padding                02
yabai -m config window_gap                   02

# Exclusions
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$"             manage=off

echo "yabai configuration loaded..."
